// Minimal androidx stub for an offline typecheck of the DropAim app sources.
// BuildConfig is GENERATED by the Android Gradle plugin from buildConfigField
// entries in app/build.gradle, so it does not exist in the source tree. These
// are the fields this app declares; keep them in step with build.gradle.
package com.dropaim.app

object BuildConfig {
    const val EXPORT_TOKEN: String = ""
    const val RELEASE_SIG: String = ""
}
